# Generated by Django 3.1 on 2020-09-13 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('Balenciaga', 'Balenciaga'), ('Burberry', 'Burberry'), ('Celine', 'Celine'), ('Chanel', 'Chanel'), ('Christian Dior', 'Christian Dior'), ('Christian Louboutins', 'Christian Louboutins'), ('Ferragamo', 'Ferragamo'), ('Givenchy', 'Givenchy'), ('Gucci', 'Gucci'), ('Hermes', 'Hermes'), ('Jimmy Choo', 'Jimmy Choo'), ('Louis Vuitton', 'Louis Vuitton'), ('Prada', 'Prada'), ('Saint Laurent', 'Saint Laurent'), ('Valentino Garavani', 'Valentino Garavani'), ('Others', 'Others')], max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=63)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=63, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('quantity', models.IntegerField(default=1)),
                ('in_stock', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
            ],
            bases=('store.product', models.Model),
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
            ],
            bases=('store.product', models.Model),
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('size', models.IntegerField(default=10)),
            ],
            bases=('store.product', models.Model),
        ),
        migrations.CreateModel(
            name='SLG',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
            ],
            bases=('store.product', models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
