# Generated by Django 3.1 on 2020-08-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200814_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Bal', 'Balenciaga'), ('Bur', 'Burberry'), ('Cel', 'Celine'), ('Cha', 'Chanel'), ('Dio', 'Christian Dior'), ('Loub', 'Christian Louboutins'), ('Fer', 'Ferragamo'), ('Giv', 'Givenchy'), ('Guc', 'Gucci'), ('Her', 'Hermes'), ('Choo', 'Jimmy Choo'), ('Vui', 'Louis Vuitton'), ('Pra', 'Prada'), ('Laur', 'Saint Laurent'), ('Gar', 'Valentino Garavani'), ('Oth', 'Others')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
    ]
