# Generated by Django 3.1 on 2020-08-14 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='id',
        ),
        migrations.AddField(
            model_name='bag',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bag',
            name='size',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(default='a'),
        ),
    ]
