# Generated by Django 3.1 on 2020-08-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200814_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test-product', max_length=200),
            preserve_default=False,
        ),
    ]
