# Generated by Django 3.1 on 2020-08-14 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('size', models.IntegerField(default=10)),
            ],
            bases=('store.product', models.Model),
        ),
        migrations.RemoveField(
            model_name='bag',
            name='size',
        ),
    ]
