# Generated by Django 3.1 on 2020-08-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_ordered',
            new_name='date_created',
        ),
    ]
