# Generated by Django 3.1 on 2020-08-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200814_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jewelery',
            new_name='Accessory',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
    ]
