# Generated by Django 3.1 on 2020-08-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage'),
        ('store', '0008_auto_20200818_1904'),
    ]

    operations = [
    ]
