# Generated by Django 3.1 on 2020-08-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_merge_20200820_2119'),
        ('store', '0009_merge_20200820_1549'),
    ]

    operations = [
    ]
