# Generated by Django 3.1 on 2020-08-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_merge_20200821_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Bal', 'Balenciaga'), ('Bur', 'Burberry'), ('Cel', 'Celine'), ('Cha', 'Chanel'), ('Dio', 'Christian Dior'), ('Loub', 'Christian Louboutins'), ('Fer', 'Ferragamo'), ('Giv', 'Givenchy'), ('Guc', 'Gucci'), ('Her', 'Hermes'), ('Choo', 'Jimmy Choo'), ('Vui', 'Louis Vuitton'), ('Pra', 'Prada'), ('Laur', 'Saint Laurent'), ('Gar', 'Valentino Garavani'), ('Oth', 'Others')], max_length=100, null=True),
        ),
    ]
