# Generated by Django 3.1 on 2020-08-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_merge_20200821_1633'),
        ('store', '0009_merge_20200821_1500'),
    ]

    operations = [
    ]
