# Generated by Django 3.1 on 2020-08-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200824_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Balenciaga', 'Balenciaga'), ('Burberry', 'Burberry'), ('Celine', 'Celine'), ('Chanel', 'Chanel'), ('Christian Dior', 'Christian Dior'), ('Christian Louboutins', 'Christian Louboutins'), ('Ferragamo', 'Ferragamo'), ('Givenchy', 'Givenchy'), ('Gucci', 'Gucci'), ('Hermes', 'Hermes'), ('Jimmy Choo', 'Jimmy Choo'), ('Louis Vuitton', 'Louis Vuitton'), ('Prada', 'Prada'), ('Saint Laurent', 'Saint Laurent'), ('Valentino Garavani', 'Valentino Garavani'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
