# Generated by Django 3.1 on 2020-08-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('store', '0011_merge_20200824_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SLGS',
            new_name='SLG',
        ),
    ]
