# Generated by Django 3.1 on 2020-08-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200824_1655'),
        ('store', '0012_auto_20200824_1717'),
    ]

    operations = [
    ]
