# Generated by Django 3.1 on 2020-12-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Ordered', 'Not Ordered'), ('In Progress', 'In Progress'), ('Shipped', 'Shipped'), ('Complete', 'Complete')], default='Not Ordered', max_length=100),
        ),
    ]
