# Generated by Django 3.1 on 2020-12-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201206_0303'),
        ('user', '0002_order_status'),
    ]

    operations = [
    ]
