# Generated by Django 3.1 on 2020-09-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200831_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(choices=[('Canada', 'Canada'), ('USA', 'USA'), ('Mexico', 'Mexico')], max_length=200, null=True),
        ),
    ]
