# Generated by Django 3.1 on 2020-09-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date_created',
        ),
    ]
