# Generated by Django 3.1 on 2020-09-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200903_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Shipping', 'Shipping'), ('Layaway', 'Layaway'), ('Pick-up', 'Pick-up')], default='Shipping', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
