# Generated by Django 3.1 on 2020-09-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200904_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='layaway',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Shipping', 'Shipping'), ('Pick-up', 'Pick-up')], default='Shipping', max_length=100, null=True),
        ),
    ]
