# Generated by Django 3.1 on 2020-09-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200905_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Shipping', 'Shipping'), ('Pick-up', 'Pick-up')], default='Pick-up', max_length=100, null=True),
        ),
    ]
