# Generated by Django 3.1 on 2020-09-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200905_1530'),
        ('user', '0006_auto_20200903_0159'),
    ]

    operations = [
    ]
