# Generated by Django 3.1 on 2020-09-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200906_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Shipping', 'Shipping'), ('Pick-up', 'Pick-up')], default='Pick-up', max_length=100, null=True),
        ),
    ]
